# Generated by Django 4.2.6 on 2023-10-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], max_length=20)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_mao_de_obra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('numero_telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadeReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('intervalo_manha', models.BooleanField(default=True)),
                ('intervalo_tarde', models.BooleanField(default=True)),
                ('intervalo_noite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('automovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.automovel')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('funcionario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade_em_estoque', models.IntegerField()),
                ('codigo_fabricante', models.CharField(max_length=255)),
                ('nome_fabricante', models.CharField(max_length=255)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('posto_trabalho', models.IntegerField(choices=[(1, 'Posto 1'), (2, 'Posto 2'), (3, 'Posto 3')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Cartão de Crédito', 'Cartão de Crédito')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manutencao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.IntegerField()),
                ('categoria_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoriaservico')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.manutencao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.produto')),
            ],
        ),
    ]
