# Generated by Django 4.2.5 on 2023-10-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_funcionario_user_alter_cliente_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadereserva',
            name='intervalo_manha',
        ),
        migrations.RemoveField(
            model_name='disponibilidadereserva',
            name='intervalo_noite',
        ),
        migrations.RemoveField(
            model_name='disponibilidadereserva',
            name='intervalo_tarde',
        ),
        migrations.AddField(
            model_name='disponibilidadereserva',
            name='posto_1_reservas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadereserva',
            name='posto_2_reservas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disponibilidadereserva',
            name='posto_3_reservas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemmanutencao',
            name='quantidade_usada',
            field=models.PositiveIntegerField(),
        ),
    ]
