# Generated by Django 4.2.5 on 2023-10-02 04:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('purchaseValue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('people', models.IntegerField()),
                ('hasPet', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendent'), ('C', 'Canceled'), ('A', 'Approved')], default='P', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('daily', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('categoryFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryTrip', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('PIX', 'PIX'), ('BS', 'BANK SLIP'), ('CC', 'CREDIT CARD'), ('CD', 'DEBT CARD')], max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendent'), ('C', 'Canceled'), ('A', 'Approved')], default='P', max_length=100)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('bookingFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookingPayment', to='main.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('tripFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripImage', to='main.trip')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('taxId', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='customUserFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customUserBooking', to='main.customuser'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tripFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripBooking', to='main.trip'),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bookingFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingAvailability', to='main.booking')),
                ('tripFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripAvailability', to='main.trip')),
            ],
        ),
    ]
