# Generated by Django 4.2.4 on 2023-08-08 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_starships_alter_planet_created_people_starship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 49, 12, 71647, tzinfo=datetime.timezone.utc)),
        ),
    ]
